export const modules = [
  {
    iconName: "Search",
    title: "Scan & Review",
    name: "Scan & Review",
    description: "Scan Databricks catalogs, detect entities, and review AI-proposed semantic definitions",
    href: "/scan",
    color: "text-[#5B7FE8]",
    iconColor: "#5B7FE8",
    bgColor: "bg-[#5B7FE8]/10",
    hoverColor: "hover:bg-[#5B7FE8]/20",
    showInNav: true,
  },
  {
    iconName: "BookOpen",
    title: "Entity Detail",
    name: "Entity Detail",
    description: "Edit metrics, dimensions, and Genie instructions for a semantic entity",
    href: "/entity",
    color: "text-[#5B7FE8]",
    iconColor: "#5B7FE8",
    bgColor: "bg-[#5B7FE8]/10",
    hoverColor: "hover:bg-[#5B7FE8]/20",
    showInNav: false,
  },
  {
    iconName: "Upload",
    title: "Publish & Versions",
    name: "Publish",
    description: "Stage, compare, and publish glossary versions to Databricks",
    href: "/publish",
    color: "text-[#5B7FE8]",
    iconColor: "#5B7FE8",
    bgColor: "bg-[#5B7FE8]/10",
    hoverColor: "hover:bg-[#5B7FE8]/20",
    showInNav: true,
  },
];
